# Generated by Django 6.0.4 on 2026-04-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
