# Generated by Django 6.0.4 on 2026-04-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='categoria',
            field=models.CharField(choices=[('sugestoes', 'Sugestões'), ('formas', 'Formas'), ('elementos', 'Elementos')], default='sugestoes', max_length=20),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
